backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: 'json'
    card: {type: "alltype", text: "title"}
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Type", name: "type", widget: "select", options: ["words", "code", "video", "audio", "photos"]}
      - {label: "BG Color Class", name: "bgcolorclass", widget: "string", required: false}
      - {label: "Text Color Class", name: "textcolorclass", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Audio", name: "audio", widget: "string", required: false}
      - {label: "Video", name: "video", widget: "string", required: false}
